spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8880
  serverAddress: localhost
  serverName: local_server

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8880
  serverAddress: 52.79.148.30
  serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8881
  serverAddress: 52.79.148.30
  serverName: green_server

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://52.79.148.30:5432/board-db
    username: board-master
    password: board-postgres-password
  security:
    user.name: board-admin
    user.password: board-admin-password
