spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret


server:
  env: blue


---


spring:
  config:
    activate:
      on-profile: local


server:
  port: 8080
  serverAddress: localhost

serverName: local_server


---


spring:
  config:
    activate:
      on-profile: blue


server:
  port: 8080
  serverAddress: 15.165.84.138

serverName: blue_server

---


spring:
  config:
    activate:
      on-profile: green


server:
  port: 8081
  serverAddress: 15.165.84.138

serverName: green_server
---



spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/board-db
    username: board-master
    password: board-postgres-password
  #logging:
  #  level:
  #    #TRACE<DEBUG<INFO<WARN<ERROR
  #    root: ERROR
  #logging:
  #  level:
  #    org.hibernate.type: TRACE
  #    org.hibernate.orm.jdbc.bind: TRACE
  #    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
  #    org.springframework.orm.jpa: DEBUG
  #    org.springframework.transaction: DEBUG
  security:
    user.name: board-admin
    user.password: board-admin-password
  config:
    activate:
      on-profile: common
